### ISSUE TITLE
JMS Client to connect to Amlen and empty a queue

### ISSUE THREAD

**Issue by emilis-venckus** [eclipse/amlen#120]
Hey all,

did anyone manage to get a ready/compiled JMS client connected to Amlen and empty a JMS queue? 

We are testing with jmstoolbox: https://github.com/jmstoolbox/jmstoolbox/releases/tag/v6.0.0.
This tool has a list of connector to different JMS Queue managers, but unfortunatelly no IMA/Amlen. Currently I am trying a connection with imaclientjms-2.0.jar based on their documentation. Will let you know how it goes.

I also have App Connect Enterprise connected to Amlen with the above JAR, but there is a need for a slim solution.

Could some part of the Amlen Code base here be used to compile a minimal JMS? Goal: connect. empty a queue of choise.
This looks close to what I need: https://github.com/eclipse/amlen/blob/main/client_jms/samples/com/ibm/ima/samples/jms/JMSSampleAdmin.java

Thanks!

**Comment by jonquark** [comment]
Hi I'm a little confused - there are JMS libraries provided for Amlen e.g. 
https://download.eclipse.org/amlen/releases/1.0.0.1/alma8/contrib/AmlenSDK-1.0.0.1-1.el8.x86_64.rpm
They can be used by:
```
export CLASSPATH=/usr/share/amlen-sdk/ImaClient/jms/lib/imaclientjms.jar:/usr/share/amlen-sdk/ImaClient/jms/lib/jms.jar:.
```
and in the same rpm there are samples for building a small jms program
```
 javac com/ibm/ima/samples/jms/JMSSample.java com/ibm/ima/samples/jms/JMSSampleReceive.java com/ibm/ima/samples/jms/JMSSampleSend.java
```
 and you can then use that 
```
 java com.ibm.ima.samples.jms.JMSSample -s tcp://<server>:16102 -q jmsq -i jmssender -a publish
```
 and
```
 java com.ibm.ima.samples.jms.JMSSample -s tcp://graviton.hursley.ibm.com:16102 -q jmsq -i jmsreceiver -a subscribe
```
 I'm not familar with jmstoolbox - but if it doesn't use the IMA client jars then it definitely won't connect (unless you can configure it to use the amlen jars)
 
 This isn't (I don't think) reporting an issue with Amlen so I'm going to close it (a better forum for discussion on JMS would be the slack channel linked from our homepage)

**Comment by emilis-venckus** [comment]
Hi Jon, yes, sorry for the confusion. Last friday I have noticed the JMS client samle myself, tested it and it works. Just forgot to comment this issue. This is somewhat the situation "read the **** manual" :) 

I will nevertheless test jmstoolbox to see if I can get it running with IMA Jars, there is a possibility to add external jars.

Thanks for pointing to slack channel. Yes, this here was not an issue, rather just a question.
