### ISSUE TITLE
Basic Auth Support

### ISSUE THREAD

**Issue by dozim** [eclipse/amlen#174]
Hello Amlen team,

I am interested in using the Amlen broker as an mqtt broker with basic auth(Username + Password) access. I have read that the broker supports LDAP, OAUTH and LTPA but as far as I understand there is no simple basic auth solution? Currently, I would not want to operate another Auth-Server if possible.  If not, is it possible to add this as an extension/plugin? The protocol plugin does not seem to be an generic extension mechnism, isn't?

**Comment by jonquark** [comment]
At the moment there is no plan to add auth directly into the server
